apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    assignment-id: {{ .Values.assignmentId }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.frontend.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.frontend.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    assignment-id: {{ .Values.assignmentId }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.frontend.fullnameOverride }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.frontend.fullnameOverride }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: INGESTION_API_URL
              value: "http://ingestion-api:8000"
            - name: PROCESSING_API_URL
              value: "http://processing-service:8001"
          resources:
            limits:
              cpu: "300m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
