apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.processingService.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.processingService.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    assignment-id: {{ .Values.assignmentId }}
spec:
  type: {{ .Values.processingService.service.type }}
  ports:
    - port: {{ .Values.processingService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.processingService.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.processingService.fullnameOverride }}
  labels:
    app.kubernetes.io/name: {{ .Values.processingService.fullnameOverride }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    assignment-id: {{ .Values.assignmentId }}
spec:
  replicas: {{ .Values.processingService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.processingService.fullnameOverride }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.processingService.fullnameOverride }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: processing-service
          image: "{{ .Values.processingService.image.repository }}:{{ .Values.processingService.image.tag }}"
          imagePullPolicy: {{ .Values.processingService.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: REDIS_HOST
              value: {{ .Values.global.redis.host | quote }}
            - name: REDIS_PORT
              value: {{ .Values.global.redis.port | quote }}
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
